services:
  serena:
    container_name: serena-container
    image: ghcr.io/oraios/serena:latest
    ports:
      - "9121:9121" # MCP server port
      - "24282:24282" # Web dashboard port
    environment:
      - SERENA_DOCKER=1
    # To work with projects, you must mount them as volumes:
    volumes:
      - ../../grava:/workspace/grava
      - ../../koban:/workspace/koban
      - ../../server:/workspace/server
      - ../../unidea-space:/workspace/unidea-space
      - ./start.sh:/start.sh:ro
    # Add the context for the IDE assistant option:
    entrypoint: [ "/bin/bash", "/start.sh" ]
